"""add image_url to products

Revision ID: 4751fe0494fa
Revises: 73982976bb89
Create Date: 2024-08-04 16:35:28.263835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4751fe0494fa'
down_revision: Union[str, None] = '73982976bb89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('image_url', sa.String(), nullable=True,
                                        default="https://developers.elementor.com/docs/assets/img/elementor-placeholder-image.png"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###
